### PR TITLE
Just a couple of fixes

### LINKED ISSUE #11: On homepage, date under "latest headlines" for each headline should be italics

### PR DESCRIPTION
**Pull request by harumhelmy**
Fixes #11, #12

With these fixes, the homepage should look like this: 
Screen Shot 2021-11-18 at 16 56 49

### CODE REVIEW

File: src/components/SectionCitations.js [hunk 1]
```diff
@@ -99,7 +99,7 @@ const SectionCitations = () => {
                     : citation.websiteTitle}
                 </Typography>
                 <Typography>
-                  {moment(citation.date).strftime("%B %e, %Y")}
+                  <em>{moment(citation.date).strftime("%B %e, %Y")}</em>
```
Comment (rudietuesdays) [inline src/components/SectionCitations.js:102]: This is a solid option for adding italics! However, for best practices, it's best to add a class to italicize the text. This is because different browsers read the `em` tag differently, so it might not show italics in every instance. I'd recommend adding a `className={classes.em}` to the `Typography` element, and then giving it the rule `fontStyle: "italic"`

**Review by rudietuesdays — COMMENTED** [review]
A couple things here! Looking great, notes are inline.

File: src/components/SectionCitations.js (hunk 1 above)
Comment (harumhelmy) [reply src/components/SectionCitations.js]: thank youuu!
